name: wecare_medics_ios
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.3
  google_maps_flutter: ^1.0.6
  mime_type:


  cupertino_icons: ^1.0.0
  http: any 
  date_time_picker: "^1.1.0"
  menu_button: ^1.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - asset/
 